### ISSUE TITLE
Getting Error, database locked

### ISSUE THREAD

**Issue by MrValioBg** [InventivetalentDev/NickNamer#106]
## What steps will reproduce the problem?  
1. Using the API, only bugs on local sql database, i have no problem with mysql.

## What were you expecting to happen? What happened instead?  
not to get error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.17.0
## What Spigot version are you using? *Type /version*  
1.15.2-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
Just the NickNamer,its dependency and my plugin

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/1UVPzgLR

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

**Comment by EXOgreen** [comment]
To elaborate on this terribly written bug report, 99% of the time this plugin works as intended. However, when I use the /reload command to refresh Minecraft datapacks and plugins, it seems NickNamer doesn't properly close/unlock the MySQL database. Once the reload is complete, the plugin can no longer make new changes to the database. 

I have opened the database with a MySQL database editor, saved and closed the DB file, reuploaded it to the server, and the plugin was able to create and save nicknames again. 

Also disturbing is that the plugin reports success to the client, but on the server, it gives the error and after the player relogs the name doesn't stick to them.
