### ISSUE TITLE
Minecraft Paper Server Plugin Crash

### ISSUE THREAD

**Issue by YTG1234** [InventivetalentDev/NickNamer#107]
## What steps will reproduce the problem?  
1. Start-Up the server.

## What were you expecting to happen? What happened instead?  
I expect the server to enable all the plugins and run.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
/3.17.0-SNAPSHOT &lt;NickNamer&gt;

## What Spigot version are you using? *Type /version*  
/PaperSpigot 1.15.2 build 143

## What plugins are you using? *Type /plugins*  
/NickNamer, PacketListenerAPI, Admin_Utils, Citizens, Cleanroom-Generator, CoreProtect, CustomCrafting, DummyFAWE, EssentialsX, EssentialsXChat, EssentialsXSpawn, FAWE, Harbor, Lib's Disguises, LuckPerms, Multiverse Core, Multiverse NetherPortals, Multiverse Portals, Multiverse SignPortals, OpenInv, Physics Control, PAPI, ProtocolLib, Scoreboard Revision, Sentinel, SimpleCompass, SuperVanish, TabList, TrollCommands++(Not working), Vault, WolfyUtilities, WorldGuard, WorldGuardExtraFlags

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/Mkxg76zY

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes! I'm using waterfall.

**Comment by YTG1234** [comment]
@InventivetalentDev

**Comment by InventivetalentDev** [comment]
What Java version are you using? I'm guessing it's probably related to that.

**Comment by YTG1234** [comment]
Sorry, it’s a plug-in crash. It failed to load. It’s failing both on Java 8 and 14

**Comment by Th3Shadowbroker** [comment]
Just an idea, but are using OpenJDK?

**Comment by YTG1234** [comment]
I think I am. I downloaded the JDK from oracle's website.

**Comment by Th3Shadowbroker** [comment]
What message do you get by typing `java -version` in your terminal/command prompt?

For comparison:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by YTG1234** [comment]
@Th3Shadowbroker I use Java 14

**Comment by Th3Shadowbroker** [comment]
Well I wouldn't recommend using Java 14. 
![image](https://user-images.githubusercontent.com/8280615/81597806-97559f00-93c6-11ea-8587-8cf6591c6b27.png)
_Java version of servers running Bukkit/Spigot_

But you said you still had problems with Java 8 which is really weird because everything's working fine for me 🤔

**Comment by YTG1234** [comment]
> Well I wouldn't recommend using Java 14.
> ![image](https://user-images.githubusercontent.com/8280615/81597806-97559f00-93c6-11ea-8587-8cf6591c6b27.png)
> _Java version of servers running Bukkit/Spigot_
> 
> But you said you still had problems with Java 8 which is really weird because everything's working fine for me 🤔

Actually I was using Java 12 before, not 1.8/8. I installed Java 8 and now it works.

**Comment by Th3Shadowbroker** [comment]
Great to hear that 👍
