### ISSUE TITLE
Feature Request, Offline nick naming

### ISSUE THREAD

**Issue by EXOgreen** [InventivetalentDev/NickNamer#111]
## This is a feature request, not a bug

When trying to nickname a player who is not on the server, the plugin gives the error that the player could not be found. Could you add the feature that after the plugin searches the active players, it also queries the playerdata folder and whitelist.json file for their UUID and append the nickname to them that way? 

For context, the reason I want this is I have a server that is whitelist only, and I am trying to set it up so when a player applies to a google form they are whitelisted to the server and it automatically names them before they join.

let me know what you think, thanks!

**Comment by InventivetalentDev** [comment]
Sounds like a neat addition!  
Gonna look into adding that :)
