### ISSUE TITLE
/nick doesn't work with EssentialsX in 1.15.2

### ISSUE THREAD

**Issue by booky10** [InventivetalentDev/NickNamer#113]
## What steps will reproduce the problem?  
1. Install EssentialsX
2. Install NickNamer
3. /nick is now used by essentials, /nicknamer:nick also doensn't work

## What were you expecting to happen? What happened instead?  
I would expect, that /nicknamer:nick would use nicknamer, but it wasn't even a command!

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.18.1-SNAPSHOT

## What Spigot version are you using? *Type /version*  
I'm using git-Paper-167 (MC: 1.15.2), API-Version: 1.15.2-R0.1-SNAPSHOT

## What plugins are you using? *Type /plugins*  
BanSQL, ChestShop, CraftBook, DisallowedCommands, dynmap*, Essentials, EssentialsT, FastAsyncWorldEdit, LibsDisguises, LobbyAPI, LootCase, LuckPerms, Matrix, MultiWorlds, Negativity, NickNamer*, NoAttackCooldown, OnlineTime, OpenInv, PacketListenerApi*, PaperT11EAPI, PlaceholderAPI, PlayerRanks*, PlugMan, ProtocolLib, RealTime, SuperVanish, SyncedMinecraftChat, T11ELobby, TabScoreboard, TrollBoss, Vault, WorldEdit, WorldEditSUI, WorldGuard

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No Errors.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm not using Bungeecord, it also didn't work in previous versions. But with Bungeecord it also isn't working.

**Comment by Th3Shadowbroker** [comment]
Hi @booky10,
I were able to replicate the described problem. I suspect the way NickNamer registers it's commands causing the problem. However there's a workaround you can use:

Disable essentials `nickname` command in your essentials `config.yml`
```yaml
disabled-commands:
  - nickname
#  - clear
```

Remap the `nick` command to `nickname` in your server `commands.yml`
```yaml
aliases:
  icanhasbukkit:
  - version $1-
  nick:
  - nickname $1-
```
