### ISSUE TITLE
Nick doesn't work in chat

### ISSUE THREAD

**Issue by GriindGaming** [InventivetalentDev/NickNamer#119]
## What steps will reproduce the problem?  
1. Install some chat plugin (I've tried ChatEX & EssentialsXChat for 1.15.2)
2.  Set the playername placehodler to the PAPI placehodler for Nicknamer
3.  write something (EssentialsXChat i tihk doesn't support placeholders that well,since it just kept the old look, with ChatEX the name just dissapeared, and never shown, even if i was nicked or not)

## What were you expecting to happen? What happened instead?  
That the name works & shows (PAPI placeholder, etc works...) What happens is that everything works, exempt the chat functions
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.18.2-SNAPSHOT
## What Spigot version are you using? *Type /version*  
git-Paper-112 (MC: 1.15.2)
## What plugins are you using? *Type /plugins*  
Chat related are: ChatEX
If you need all plugins, please leave a reply
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No, I don't
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No, I didn't
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using Waterfall BungeeCord fork, but it was the same when I only used normal Spigot

I do understand that this may be a fault with PAPI, or ChatEX as well

**Comment by Th3Shadowbroker** [comment]
Hello @GriindGaming,
thank you for reporting this problem. 

> What happens is that everything works, exempt the chat functions

What message do you get when you're running `/papi parse <username> %nicknamer_nickname%`?
Are you using the NickNamer eCloud expansion? If that's the case please uninstall it. NickNamer comes with it's own expansion. Please let me know if this solved your problem.

**Comment by GriindGaming** [comment]
Hello, sorry that I'm late, but I have now tested the parse command, and it comes up with my name, however I installed the eCloud expansion because I didn't find any expansions that came with the plugin. And the parse command only works when the eCloud expansion is installed.

I nicked myself "test" and tried the parse command with & without the eCloud expansion and the results were that it came us with "test" when it was installed, however when it was not it just gave me the placeholder.

**Comment by Th3Shadowbroker** [comment]
Mhhhh.... 🤔 
I can't replicate what you described. I only have NickNamer and its requirements installed and the placeholders work accordingly.

> I didn't find any expansions that came with the plugin. 

There's nothing to find. It's included in the plugin itself 🙂

**Comment by GriindGaming** [comment]
Hmm... What chat plugin do you use then? I have tried both EssentialsXChat and ChatEX.

**Comment by GriindGaming** [comment]
Because for me, it works in the Scoreboard (Side list), it's only in the chat that it doesn't show anything

**Comment by Th3Shadowbroker** [comment]
Sorry! I forgot to test ChatEx. I were totally focused on the placeholders 😅 

I'm using EssentialsXChat. The problem with EXC is, that it does not support PlaceholderAPI so you have to configure NickNamer to replace names in all outgoing messages. (Like in the example below 🔽)

**NickNamer** _(config.yml)_
```yaml
replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: true <-- This will to the trick
```

If you want to use ChatEx instead this (🔼 ) will also work. You just have to to replace the `%player` placeholder with `%displayname` like this:
**ChatEx** _(config.yml)_
```yaml
message-format: '%prefix%displayname%suffix: %message'
global-message-format: '&9[%world] %prefix%displayname%suffix: &e%message'
```
I honestly don't know why PlaceholderAPI placeholders do not work at this point 😅 

Please let me know if this solved your problem 🙂

**Comment by GriindGaming** [comment]
Aight, I'll try

**Comment by GriindGaming** [comment]
Yeah, It kinda works, but I see three problems with this unfortunately...
http://prntscr.com/skkffi

As you can see the suffix is doubled, this can be fixed by just removing the extra "%suffix"  although,  the suffix is straight on the name instead of a space, and I want an automatic space to make it as easy to add a new group/prefix, suffix, etc as possible.

The third problem is that here you can see my actual IGN, instead of showing me the nicked name.

Right now I have just edited the chatex config, but yeah.

The reason why I have ChatEX right now, is because the same problem is with EssentialXChat for me...

**Comment by Th3Shadowbroker** [comment]
Forget what I said about the `%displayname`. It just worked in my case because I have no plugin manipulating the displayname by attaching the groups to it. `%player` should work! 😅 

*ChatEx* _(config.yml)_
```yaml
message-format: '%prefix%player%suffix: %message'
global-message-format: '&9[%world] %prefix%player%suffix: &e%message'
```

**Comment by GriindGaming** [comment]
Aight, I'll try

**Comment by GriindGaming** [comment]
Do I still have to turn on all messages though?

**Comment by Th3Shadowbroker** [comment]
Yes

**Comment by GriindGaming** [comment]
Aight, I see one potential problem though... If someone types the real name of the player they might be able to know that they're nicked as that player because they see that their message changed?

Correct me if I'm wrong...

**Comment by GriindGaming** [comment]
Also, is there any other dependencies other than the spigot nicknamer plugins to be able to use the bungeecord synchronizer? Right now it ain't working...

**Comment by Th3Shadowbroker** [comment]
> Also, is there any other dependencies other than the spigot nicknamer plugins to be able to use the Bungeecord synchronizer? Right now it ain't working...

Installing the [sync.-plugin](https://www.spigotmc.org/resources/nicknamer-bungee-synchronizer.8964/) and making sure `bungeecord` in the spigot.yml and NickNamers config.yml as well as `ip_forward` in your BungeeCord config.yml are set to true should work 🤔 

> Aight, I see one potential problem though... If someone types the real name of the player they might be able to know that they're nicked as that player because they see that their message changed?
> 
> Correct me if I'm wrong...

Feel free to create an issue 🙂

**Comment by GriindGaming** [comment]
Aight, is the MYSQL needed if I'm running it bungee?

**Comment by GriindGaming** [comment]
Nvm, I think I got it...

**Comment by GriindGaming** [comment]
Weird... I got all those things enabled and installed and it doesn't work?

**Comment by GriindGaming** [comment]
Nvm fixed it... Just suddenly started working, lol.

**Comment by Th3Shadowbroker** [comment]
Nice! 👍
