### ISSUE TITLE
TabComplete Error

### ISSUE THREAD

**Issue by Sprax2013** [InventivetalentDev/NickNamer#13]
## What steps will reproduce the problem?
1. Use /nick NAME - to get a Nick (make sure TabComplete is false in config)
2. Try to TabComplete youre original InGameName (Will TabComplete to youre new NickName)
3. Try TabComplete youre new NickName (Won't TabComplete anything)
## What were you expecting to happen? What happened instead?

That the new Nick would be TabCompletet not my Original name
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

latest (3.11.7)
## What Spigot version are you using? _Type /version_

CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
## What plugins ae you using? _Type /plugins_

Plugins (4): PermissionsEx, EmptyWorldGenerator, ServerUtils, LobbyHandler (Last two are my own [Only WorldManager, LobbyItems, ... and some Utils collected in ServerUtils])
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No error
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No Client/Server crash
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Using BungeeCord last build - tryed sqg and local database

**Comment by sebastianbinder** [comment]
I can confirm this one.
