### ISSUE TITLE
NickNamer not working

### ISSUE THREAD

**Issue by likseBSMC** [InventivetalentDev/NickNamer#135]
## What steps will reproduce the problem?  
1. Load the plugin
2. Run a nick/skin command

## What were you expecting to happen? What happened instead?  
I expected my nick or skin to be set.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.18.4-SNAPSHOT
## What Spigot version are you using? *Type /version*  
Spigot 1.16.2 Latest
## What plugins are you using? *Type /plugins*  
NickNamer, PlugMan, NBTAPI, PacketListenerApi, ProtocolLib, Vault, PermissionsEx

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/hDXV9WwV
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope.

**Comment by TrollyLoki** [comment]
This was fixed in version 3.18.5-SNAPSHOT (#136)
