### ISSUE TITLE
Library issue For 1.15.2 at least

### ISSUE THREAD

**Issue by RedDragon204** [InventivetalentDev/NickNamer#138]
## What steps will reproduce the problem?  
1. I didn't fine it, my server support did
2. 
3. 

## What were you expecting to happen? What happened instead?  
The plugin just isn't there for a library issue
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
The 1.15.2 version for my sever
## What Spigot version are you using? *Type /version*  
1.15.2
## What plugins are you using? *Type /plugins*  
Just the NickName Plugin
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/k5LX6Scp
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I have no other info

**Comment by Th3Shadowbroker** [comment]
Hi @RedDragon204,
I were unable to replicate the issue you described. According to your issue, you are missig [PacketListenerAPI](https://www.spigotmc.org/resources/api-packetlistenerapi.2930/). Please make sure that PacketListenerAPI and NickNamer are both up2date and your server is running oracle jre version 8.
