### ISSUE TITLE
Plugin won't start

### ISSUE THREAD

**Issue by B1ueN0va** [InventivetalentDev/NickNamer#139]
## What steps will reproduce the problem?  
1. Go on 1.8.8 Paper Spigot Server
2. Put in the Newest Nick Namer Jar
3. Start up the server

## What were you expecting to happen? What happened instead?  
I expected the plugin to work, it didn't
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
The newest version; v3.18.5-SNAPSHOT
## What Spigot version are you using? *Type /version*  
Paper Spigot 4c7641d
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/70184629/94713873-39d3d780-0300-11eb-92a5-d2894678fdfb.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/8eGxTWk7
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using Paper Spigot if you couldn't tell.

**Comment by Th3Shadowbroker** [comment]
Hey @B1ueN0va,
I've checked your log and it looks like you're missing a dependency. Please install [PacketListenerAPI](https://www.spigotmc.org/resources/api-packetlistenerapi.2930/).
