### ISSUE TITLE
As of 3.19, user join/leave messages are not displayed

### ISSUE THREAD

**Issue by jennasisis** [InventivetalentDev/NickNamer#149]
## What steps will reproduce the problem?  
1. Install NickNamer version 3.19
2. Join or leave a server
3. Observe

## What were you expecting to happen? What happened instead?  
Expected:
`User joined the game.`

Actually:
nothing, no message.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.19.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Paper version git-Paper-505 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Chairs, CoreProtect, floodgate-bukkit, Geyser-Spigot, ImageMaps, LuckPerms, NickNamer*, PacketListenerApi*, PlugMan, ViaBackwards, ViaVersion, WorldEdit

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No error log. Just nothing,

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No? Was it supposed to? lol

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No bungeecord, seemed to work in 3.18 but the coloring was off (name was yellow, rest of the message was white). I didn't really care about the coloring, but join/leave messages are pretty handy to know who is online lol

**Comment by Th3Shadowbroker** [comment]
Hey there, 
I were able to replicate this behaviour using Paper build 505 and 526.
However, both messages are working normally with build 471.
I'll let you know if I know more 🙂

**Comment by Th3Shadowbroker** [comment]
I've drafted a message fallback to bypass this problem.
For some reason the original join and leave messages were empty.
As I mentioned before, this problem seems to be somehow connected to the server version 🤔

**Comment by jennasisis** [comment]
Strange. I'll see if I can replicate with paper 471 just to confirm..

**Comment by Th3Shadowbroker** [comment]
@jennasisis Were you able to replicate it? It seems it really is Paper specific. I haven't had any problems with Spigot.

**Comment by jennasisis** [comment]
Seems I don't need to anymore, as of paper 545 the problem doesn't exist.

**Comment by Th3Shadowbroker** [comment]
Happy to hear that!
Just tested it myself and it works as it's supposed to 👍🏼 
They fixed the bug and that is definitely cleaner than needing a fallback 🙂 
I think you can close this issue @jennasisis 🙂 
cc: @InventivetalentDev
