### ISSUE TITLE
Plugin not launching

### ISSUE THREAD

**Issue by JSRJSR** [InventivetalentDev/NickNamer#154]
Hi there
I was hopping you could provide some asstince, I will just quickly walk though the short life of this sever to just explain all things esplcily if one of them is cousing this issue

So the server runs on a diggiteal ocean Droplet, It started and a plan vanilla server were it has run for about 3 weeks, after that time a made a new Spigot server but useing the world form the vanilla server world as this is all for a event that is being hosted in Minecraft and Discourd.

I have downloaded the api and the main .jar file in and neather seem to be booting, and when I run a /pl command in game or the pl command in the consle I resive the 0 plugin message. I have also tryed to install lukyperms that world first time not problems.

I have a lot of expreance running vanille servers as well as have exprence with codeing and working in comand promts, so complicated is okay.

Hope you or some one can help
James

**Comment by Th3Shadowbroker** [comment]
Hi James,
I have a few questions:
1. Which Spigot version are you using?
2. Which JDK are you using (Oracle or OpenJDK)?
3. Could you provide us with a log file (I'd recommend using [pastebin](https://pastebin.com/), or [gist](https://gist.github.com/))?

**Comment by JSRJSR** [comment]
1.
1.15.2 (I am dum)
2. 
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
3.
https://pastebin.com/kz60yud2

And a pre thanks for you help

**Comment by Th3Shadowbroker** [comment]
According to line 13 of your log:
>[22:20:28] [Server thread/ERROR]: Could not load 'plugins/PacketListenerAPI_v3.8.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/inventivetalent/packetlistener/PacketListenerPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

it seems, that you java version is outdated, which prevents PacketListenerAPI and NickNamer from loading.
I'd recommend upgrading to java 11 🙂

**Comment by JSRJSR** [comment]
Mate you are amazing I will have a try it out in a few hours we have a meeting know that does not allow me to shut it down and do the update, I will let you know of the outcome.
agian thankf for your help
James
