### ISSUE TITLE
Plugin won't make a folder

### ISSUE THREAD

**Issue by MrSpiderz** [InventivetalentDev/NickNamer#157]
## What steps will reproduce the problem?  
1. Use 1.16.5 Tuinity Server
2. Put the nicknamer and packetlisenerAPI jar
3. Restart the server

## What were you expecting to happen? What happened instead?  
The plugin would create a folder. It didn't work.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.20.0-SNAPSHOT
## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/84100098/118033133-11986680-b32e-11eb-942e-440c6a79371f.png)

## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/84100098/118033181-22e17300-b32e-11eb-8de9-f9b70ee3a3d6.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/2u98LgsZ
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No, and Idk.

**Comment by Th3Shadowbroker** [comment]
Hi @MrSpiderz,
I see multiple issues here.

**Regarding NickNamer:**
According to line 34 of your log, your java version is outdated. I'd recommend upgrading to java 11.

**Other plugins:**
Line 17 and 18 show, that you also have the same plugins more than once in your `plugins` directory.
Also: HologramsPlayeholder requires Holograms (Line 19 + 20) and the plugin named CreatorCodes is invalid because of an invalid name (Line 16).

**Comment by MrSpiderz** [comment]
Thank you! I will try and fix those.

**Comment by MrSpiderz** [comment]
Quick question how do I update my java on a web host?

**Comment by Th3Shadowbroker** [comment]
Totally depends on the hoster and type of server. If it is a root server you can easily google it, but if it's a MC server hoster I'd recommend checking their web-interface for an option and/or getting in touch with the support.

**Comment by MrSpiderz** [comment]
Ok thank you.

**Comment by MrSpiderz** [comment]
Its working now thank you very much!
