### ISSUE TITLE
NickNamer/PacketListenerAPI not working

### ISSUE THREAD

**Issue by skulltraill** [InventivetalentDev/NickNamer#158]
Hi, here's the error I get:

`22.05 23:53:56 [Server] INFO [NickNamer] Enabling NickNamer v3.21.0-SNAPSHOT*
22.05 23:53:56 [Server] INFO [APIManager] API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
22.05 23:53:56 [Server] ERROR Error occurred while enabling NickNamer v3.21.0-SNAPSHOT (Is it up to date?)
22.05 23:53:56 [Server] INFO java.lang.ClassCastException: class org.inventivetalent.packetlistener.PacketListenerAPI cannot be cast to class org.inventivetalent.apihelper.API (org.inventivetalent.packetlistener.PacketListenerAPI is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @24993f03; org.inventivetalent.apihelper.API is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3d29190c)
22.05 23:53:56 [Server] INFO at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:116) ~[?:?]
22.05 23:53:56 [Server] INFO at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:183) ~[?:?]
22.05 23:53:56 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-"1f28e6eeb"]
22.05 23:53:56 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
22.05 23:53:56 [Server] INFO [NickNamer] Disabling NickNamer v3.21.0-SNAPSHOT`

NickNamer Version: v3.21.0
PLAPI Version: v3.9.0
Server Version: This server is running Paper version git-Paper-"1f28e6eeb" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Java Version: 11

**Comment by zenandreas** [comment]
same error here

**Comment by InventivetalentDev** [comment]
try using an older version of both plugins or update to java 16

**Comment by zenandreas** [comment]
> try using an older version of both plugins or update to java 16

i have literally tried last 10 versions and none work. Same error. I don't want to update to java 16 i'm fine with java 11.

**Comment by jan-kir-wwu** [comment]
Same error here with 
- Java 16
- Packetlistener API 3.9.0+
- Lates Nicknamer 3.2.1

**Comment by jan-kir-wwu** [comment]
> try using an older version of both plugins or update to java 16

Same error here with

Java 16
Paper-741 1.16.5
Packetlistener API 3.9.0+
Lates Nicknamer 3.2.1

**Comment by FranklinL** [comment]
Same error here even on Java 16. My current workaround is to use Paper-671 or earlier or PurPur 1110 or earlier with 3.20.0-SNAPSHOT and Packetlistener API 3.8.0-SNAPSHOT. Anything newer (either Paper or NickNamer/Packetlistener) doesn't work together.
