### ISSUE TITLE
An exception occured while trying to execute 'onSend' in plugin NickNamer. Error.

### ISSUE THREAD

**Issue by TheRealGriind** [InventivetalentDev/NickNamer#166]
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Nicknamer 3.21.1-SNAPSHOT & Packetlistener API 3.9.3-SNAPSHOT
## What Spigot version are you using? *Type /version*  
This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 5 version(s) behind
## What plugins are you using? *Type /plugins*  
http://prntscr.com/1gpnph6
Many of them are newer additions than the problem itself.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://paste.revivenode.com/wosacagufe.sql
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No, but it kicks me out of the server sometimes for absolutely no reason, either saying that I sent too many packets, or
that the server went down and just kicks me to the hub server, even though the server never shuts down.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using Bungeecord. This error has been there for quite a while, not really causing a problem other
than a few random kicks while joining the server (see above) and a bit of annoyance with spamming the console & logs with that error.

**Comment by InventivetalentDev** [comment]
might be able to "fix" it for now by disabling the scoreboard replacements in the config

**Comment by GriindGaming** [comment]
Hmm, that's weird, cause scoreboard replacements are already disabled. http://prntscr.com/1i43w9f
