### ISSUE TITLE
Disappearing world

### ISSUE THREAD

**Issue by JackkGC** [InventivetalentDev/NickNamer#18]
## What steps will reproduce the problem?
1. Version 1.9.4
2. Nick yourself

## What were you expecting to happen? What happened instead?  
To be nicked normally.
The world disappeared.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.11.8

## What Spigot version are you using? *Type /version*  
1.9.4

## What plugins are you using? *Type /plugins*  
PacketListenerAPI/NickNamer/NickNamer - Bungee synchronizer
Anything else isn't important.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No. It's possible to crash the players client? Can you tell me how? :D Would be cool against hackers!
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
In previous version there was a feature to disable instant self update (skin). It's removed in the new ones (I didn't update for a while). A while ago I very actively suggested stuff a.s.o. and I reported the issue. You added that feature. Now I updated and it's gone :D

**Comment by InventivetalentDev** [comment]
Feature re-added in v3.12.1. (Note: There's still no proper way to avoid the world disappearing)
