### ISSUE TITLE
TabList scoreboard

### ISSUE THREAD

**Issue by Kurimatzu** [InventivetalentDev/NickNamer#20]
# What steps will reproduce the problem?  
1. Using the/nick command
2. Using /nm command. (NameManager plugin)
3. 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NickNamer version 3.12.1
## What Spigot version are you using? *Type /version*  

This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  

 Plugins (5): NameManager, PacketListenerApi, NickNamer, ProtocolSupport, ViaVersion

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

Even with the option scoreboardTeam: true, the scoreboard in the tablist, does not appear.

I'm using the NameManager as scoreboard system.

**Comment by InventivetalentDev** [comment]
Could you please answer the **steps to reproduce** and **What did you expect, what happened instead?** questions?
I'm not sure what the issue is about at the moment.

**Comment by Kurimatzu** [comment]
@InventivetalentDev 

Edited.

Well, after relogin to the server, the scoreboard started working perfectly.
I think that is related to the updateSelf: true.

(could always use the UUID of the player, instead of UUID. randomUUID ()?, is generating incompatibility with other plugins.

**Comment by InventivetalentDev** [comment]
So, what does your scoreboard look like? Does it contain player names that are supposed to be replaced when you nick the players?  
Could you please link me the code where I use _randomUUID_?

**Comment by Kurimatzu** [comment]
@InventivetalentDev The player's nickname is blank, no scoreboard.

I said about the UUIDS, because when used NamegTagEdit, said Cloud not found UUID% s.

**Comment by InventivetalentDev** [comment]
Sorry, but I'm still not sure what the issue is. Is it about the actual scoreboard or the player list (tab-list)? 
Could you maybe post some screenshots of what's wrong?  
NickNamer doesn't do anything with random UUIDs and I also don't know exactly how NameTagEdit works, so it might be an issue with that plugin.

**Comment by Kurimatzu** [comment]
Before using or  /nick:

http://i.imgur.com/ro6hK0O.png

After using the/nick:

http://i.imgur.com/lUS1j7l.png

**Comment by InventivetalentDev** [comment]
Please [paste](http://pastebin.com/) your config.yml.

**Comment by Kurimatzu** [comment]
http://pastebin.com/0RvC9Did

**Comment by InventivetalentDev** [comment]
I see what the issue is now.  But it doesn't seem like a too major problem, as other players properly see prefixes/suffixes. (Only for yourself it's shown differently)

**Comment by Kurimatzu** [comment]
@InventivetalentDev  There's how to fix it?

**Comment by InventivetalentDev** [comment]
The only way to fix is probably modifying the NameManager plugin. I don't see a reason to fix anything about it, as the names are still properly displayed for all other players on the server.

**Comment by Kurimatzu** [comment]
@InventivetalentDev You can review the code to find a possible solution?

I will find another plugin of scoreboards.

**Comment by InventivetalentDev** [comment]
As I said, I don't see a reason to _fix_ this.

**Comment by Kurimatzu** [comment]
@InventivetalentDev The updateSelf should work correctly, and not by "half"

**Comment by InventivetalentDev** [comment]
That's not what updateSelf does. It's a feature that properly refreshes your skin, so you can see it yourself without having to relog.
