### ISSUE TITLE
Nick Name Change

### ISSUE THREAD

**Issue by MrCosgrove1** [InventivetalentDev/NickNamer#22]
## What steps will reproduce the problem?  
1. Do /nick
2. 
3. 

## What were you expecting to happen? What happened instead?  
I want to change my name and then my Name just leave blank :(
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.12.1
## What Spigot version are you using? *Type /version*  
git-spigot-9797151-301db84 MC: 1.10.2 Implementing API version 1.10.2 R0.1 Snapshot
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
no
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Yes I'm using Bungeecord and here is my config:  http://pastebin.com/UM1a3KEv

**Comment by InventivetalentDev** [comment]
Please specify the _exact_ commands you executed. Just `/nick` will give you a 'missing argument' message, so that won't cause any issues.
_Where_ is the name blank? Please provide some screenshots if that's easier.

**Comment by MrCosgrove1** [comment]
I used /nick Test Mr_Cosgrove
http://prntscr.com/budbne
http://prntscr.com/budbv7

**Comment by InventivetalentDev** [comment]
Might be an issue with the 'sql' storage type. Could you please try deleting the `nicknamer_...` tables, and see if that works?

**Comment by MrCosgrove1** [comment]
Same Error again :/

**Comment by MrCosgrove1** [comment]
Same Problem again :/

**Comment by MrCosgrove1** [comment]
God Damn .... I found the problem... I'm an idiot, sorry
names:
  # Format for names, for example '&9%s' would color all names blue. Note: names can't be longer than 16 charcters and will be shortened.
  format: ""

I leave it empty cause I want normal name....without colors... I tried it now with &r


Sorry for wasting Time

**Comment by InventivetalentDev** [comment]
I see, no problem :)  
I'll add a check for that in the next update.
