### ISSUE TITLE
isNicked() always true

### ISSUE THREAD

**Issue by Sprax2013** [InventivetalentDev/NickNamer#23]
## What steps will reproduce the problem?  
1. use org.inventivetalent.nicknamer.api.NickNamerAPI.getNickManager().isNicked(); in own Plugin
2. use /nick and /nickclear
3. Output value of isNicked()/hasSkin() in Chat on ToggleSneakEvent

## What were you expecting to happen? What happened instead?  
isNicked/hasSkin is always true - Also after /clearnick or /skinclear

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.12.1
## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
Plugins (8): PermissionsEx, EmptyWorldGenerator, ServerUtils, PacketListenerApi, ProtocolLib, NoCheatPlus, NickNamer, LobbyHandler
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No error log

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No crash
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Using BungeeCord (Plugins on BungeeCord: movemenow-1.2-17, NickNamerBungee_v1.0.3, etc.)

**Comment by InventivetalentDev** [comment]
Which storage type are you using?

**Comment by Sprax2013** [comment]
local

**Comment by InventivetalentDev** [comment]
Fixed in v3.12.2.
