### ISSUE TITLE
ProfileDisguiseEvent - Unable to find handler list

### ISSUE THREAD

**Issue by Sprax2013** [InventivetalentDev/NickNamer#24]
## What steps will reproduce the problem?  
1. use the org.inventivetalent.nicknamer.api.event.disguise.ProfileDisguiseEvent
## What were you expecting to happen? What happened instead?  
To be able to use the Event instead Spigot is giving me an error
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NickNamer version 3.12.2
Author: inventivetalent
## What Spigot version are you using? *Type /version*  
 This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
PermissionsEx, EmptyWorldGenerator, ServerUtils, PacketListenerApi, ProtocolLib, NoCheatPlus, NickNamer, LobbyHandler
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/ZVBy0thr
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
didn't crash
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
- latest BungeeCord
- Bungee synchronizer
- storage: local

**Comment by InventivetalentDev** [comment]
The `ProfileDisguiseEvent` is an _abstract_ class, which is extended by [`NickDisguiseEvent`](http://ci.inventivetalent.org/job/NickNamer/javadoc/org/inventivetalent/nicknamer/api/event/disguise/NickDisguiseEvent.html) and [`SkinDisguiseEvent`](http://ci.inventivetalent.org/job/NickNamer/javadoc/org/inventivetalent/nicknamer/api/event/disguise/SkinDisguiseEvent.html). 
You have to listen for those events instead.
