### ISSUE TITLE
Colored nickname problems

### ISSUE THREAD

**Issue by Vert3xIT** [InventivetalentDev/NickNamer#30]
## What steps will reproduce the problem?
1. I use a colored nickname and I type correctly any command that targets myself
2. I lose connection with "Illegal characters in chat" also if, tab-completing, the name was appearing normally, this in fact happens only after executing any command.
## What were you expecting to happen? What happened instead?

I was expecting that my name was appearing as I set but with no colors to prevent this, this, in part, happened showing my original name but I lost connection anyway.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

3.12.2
## What Spigot version are you using? _Type /version_

1.10.2
## What plugins are you using? _Type /plugins_

ActionAnnouncer, AdvancedMotd, BarAPI, BetterAlias, ChatColor2, ChestCommands, ClearChat, Climb, CrackShot, CraftBook, DeathMessages, EpicRename, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FakeMessages, FancyTNT, FieryInferno, HealthBar, Herobrine, HolographicDisplays, iDisguise, IronDoorOpener, mcMMO, MineAPI, Multiverse-Core, MyCommand, NickNamer, NoSwear, PacketListenerApi, PermissionsEx, PlaceholderAPI, PlugMan, Psychokinesis, SimpleProjectile, Skins, SpawnJoin, SuperVanish, TagAPI, ThrowableTNT, ThrowBlocks, Thrower, Vault, VirtualPack, WorldEdit, WorldGuard.

**Comment by InventivetalentDev** [comment]
Could you please post some of the commands you used? 
If you used the /randomNick commands, please also upload your config.yml.

**Comment by Vert3xIT** [comment]
No I just use /nickname (which is an alias that I removed form essentials: /nick cannot be removed) and a colored name par example /nickname &1&lVert3x and everything seems to work but when I type a command where I specify me par example /kill Vert3x or /seen Vert3x I lose connection with the error "Illegal characters in chat". I think that something as this should happen when tab-completing my name and crashing because colored text isn't supported in my personal chat; but this crash happens only after typing that command probably the problem is that it has a problem registering this on history (when you open chat with "T" and you press the up key): I didn't use /randomNick for this, anyway I don't know how to upload my config file so I'll just paste it in a code block:
`replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: true
    in:
      # Replace names in incoming commands
      command: true

      # Replace names in general (non-command) incoming messages
      general: true
  scoreboard: true
  scoreboardScore: true
  scoreboardTeam: true
  tabComplete:
    chat: true

updateSelf: true

random:
  join:
    nick: false
    skin: false
  nick:
  - "inventivetalent"
  - "md_5"
  - mojang:
    - "jeb_"
    - "Notch"
    - "Dinnerbone"
  skin:
  - "md_5"
  - "inventivetalent"

names:
  # Format for names, for example '&9%s' would color all names blue. Note: names can't be longer than 16 charcters and will be shortened.
  format: "%s"

  # Format for names in chat messages
  chatFormat: "%s&r"

#Enable this if this server is behind a BungeeCord server
bungeecord: false

storage:
  # Storage type
  # - temporary
  #     saves all data in memory until the server is stopped
  # - local (recommended)
  #     creates a local database or uses the database specified in bukkit.yml
  # - sql
  #     uses an SQL server
  # - redis
  #     uses a Redis server
  type: "local"
  sql:
    address: "jdbc:mysql://localhost:3306/minecraft"
    user: ""
    pass: ""
  redis:
    host: "localhost"
    port: 6379
    pass: ""
    max-connections: 4


messages:
  command:
    name:
      changed: "&9NickNamer> &6Il nome di &c%player%&6 è stato cambiato in &c%name%&6."
      cleared: "&9NickNamer> &6Cancellato il nome di &c%player%&6."
      list:
        used: "&6Nomi usati:"
        format: "&c%s &6è usato da&c %s"
      error:
        length: "&9NickNamer> &cIl nome specificato è troppo lungo."
        category:
          unknown: "&9NickNamer> &cCategoria sconosciuta: %s"
        list:
          empty: "&cNon ci sono nicknames usati."
    skin:
      changed: "&9NickNamer> &6La skin di &c%player% &6è stata cambiata in quella di &c%skin%&6."
      cleared: "&9NickNamer> &6Cancellata la skin di &c%player%&6."
      list:
        used: "&6Nomi skin usate:"
        format: "&c%s &6è usato da&c %s"
      error:
        length: "&c&9NickNamer> La skin specificata ha il nome troppo lungo."
        category:
          unknown: "&9NickNamer> &cCategoria sconosciuta: %s"
        list:
          empty: "&cNon ci sono skins usate."
    error:
      unknown: "&cSi è verificato un errore sconosciuto eseguendo questo comando. Vedi la console per maggiori informazioni."
      permission: "&cNon hai la seguente autorizzazione: %s"
      illegalSender: "&cQuesto comando può essere eseguito solo dai giocatori."
      unhandled: "&cEccezione interna. Vedi la console per maggiori informazioni."
      length:
       short: "&9NickNamer> &cArgomenti insufficienti. Uso corretto: %s"
       long: "&9NickNamer> &cTroppi argomenti. Uso corretto: %s"
      parse: "&9NickNamer> &cL'analisi degli argomenti è fallita: '%s' a %s"
      target:
        notFound: "&9NickNamer> &cGiocatore non trovato."

# Disable the features below, if you're only interested in utilizing the API.
pluginFeatures:
  commands:
    general: true
    nick: true
    skin: true
`
(I translated messages to my language and adding a manual plugin prefix)
