### ISSUE TITLE
Developer API doesn't work

### ISSUE THREAD

**Issue by theonlygusti** [InventivetalentDev/NickNamer#31]
In my player listener class for my own plugin:
```java
// ...
import org.inventivetalent.nicknamer.api.SimpleNickManager;
// ...
public void onPlayerJoin(PlayerJoinEvent event) {
  Player player = event.getPlayer();
  UUID uuid = player.getUniqueId();
  String rank = MyPlugin.getPlayerRank(player); // This works and returns, for example, "§6§lOWNER§r"
  
  SimpleNickManager nameAboveHead = new SimpleNickManager(new MyPlugin());
  nameAboveHead.setNick(uuid, rank + player.getName());
  // the line of code above throws the error
}
```

I am expecting that when I run the server (using craftbukkit 1.10) and a player joins the name above their head will no longer be "NoobDoesMC" but instead "OWNER NoobDoesMC", where "OWNER" is coloured gold.

Instead, whenever a player joins craftbukkit throws this error:

```
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:101) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[craftbukkit-1.10.jar:git-Bukkit-10c10b3]
        at io.github.theonlygusti.myplugin.MyPlugin.<init>(WizardServer.java:16) ~[?:?]
```
 
Using version 5.1.6 of NickNamer as a maven dependency (my pom.xml contains):

```xml
<repository>
  <id>inventive-repo</id>
  <url>https://repo.inventivetalent.org/content/groups/public/</url>
</repository>

<dependency>
  <groupId>org.inventivetalent.nicknamer</groupId>
  <artifactId>api</artifactId>
  <version>3.12.2</version>
</dependency>
```

Maven is set to build a jar with dependencies.

## What Spigot version are you using?  
craftbukkit1.10.jar

## What plugins are you using?
WorldEdit, MyPlugin, VoxelSniper

**Comment by theonlygusti** [comment]
Note: `MyPlugin` extends `org.bukkit.plugin.java.JavaPlugin` but does not have its own constructor.

**Comment by theonlygusti** [comment]
##It would be most helpful if you could just show me how I am meant to use your plugin's API to set a player's name above their heads.

**Comment by InventivetalentDev** [comment]
There are examples on how it's intended to use the simple nick API in the plugin's description.  
You cannot create new instances of classes extending JavaPlugin, Bukkit does not allow that, that's why you get an exception.
You are also not supposed to create a new instance of the SimpleNickManager. If you want to use it, you can get its instance via `NickNamerAPI.getNickManager()`.

**Comment by theonlygusti** [comment]
OK so I changed the lines

```java
SimpleNickManager nameAboveHead = new SimpleNickManager(new MyPlugin());
nameAboveHead.setNick(uuid, rank + player.getName());
```

to the line

```java
NickNamerAPI.getNickManager().setNick(uuid, rank + player.getName());
```

and I imported org.inventivetalent.nicknamer.api.NickNamerAPI

Now craftbukkit throws this error on a player's join event:

```
Caused by: java.lang.NullPointerException
        at io.github.theonlygusti.wizardserver.PlayerListener.onPlayerJoin(PlayerListener.java:77) ~[?:?]
```

**Comment by InventivetalentDev** [comment]
What's on line 77 of your PlayerListener class?

**Comment by theonlygusti** [comment]
NickNamerAPI.getNickManager().setNick(uuid, rank + player.getName());

**Comment by InventivetalentDev** [comment]
Probably the NickManager or `player` is null. 
Make sure you have the NickNamer plugin installed and declared as a dependency in your plugin.yml.

**Comment by theonlygusti** [comment]
I don't want to have to do that, why isn't referencing the dependency via Maven enough?

**Comment by InventivetalentDev** [comment]
Because you are using the NickManager.  

As I said, an example on how to use _just the simple api, without the plugin_ is in the plugin's description.

**Comment by theonlygusti** [comment]
I'm sorry for being a pain, but I literally have no idea how to use the API. I just added this to my PlayerListener class:

```java
@EventHandler
public void on(NickDisguiseEvent event) {
  event.setNick("inventivetalent");
}```

it does nothing, and it is literally all I can see in the example you keep referencing.

**Comment by InventivetalentDev** [comment]
Did you register your events properly? Does the event get called at all?  

If you're still trying to do it without NickNamer installed, I think you need to register it using APIManager. The instructions should be somewhere in the description.

**Comment by InventivetalentDev** [comment]
Well, I must have removed them at some point. You can take a look at the [PacketListenerAPI example](https://apimanager.inventivetalent.org/info/?data=ew0KCSJuYW1lIjogIlBhY2tldExpc3RlbmVyQVBJIiwNCgkiZGVwZW5kIjogW3sNCgkJIm5hbWUiOiJQYWNrZXRMaXN0ZW5lckFwaSIsDQoJCSJjbGFzcyI6ICJQYWNrZXRMaXN0ZW5lckFQSSIsDQoJCSJncm91cElkIjogIm9yZy5pbnZlbnRpdmV0YWxlbnQucGFja2V0bGlzdGVuZXIiLA0KCQkiYXJ0aWZhY3RJZCI6ICJhcGkiLA0KCQkidmVyc2lvbiI6ICIlJWxhdGVzdCUyOTMwIg0KCX0sDQoJew0KCQkiZ3JvdXBJZCI6ICJvcmcuaW52ZW50aXZldGFsZW50LnBhY2tldGxpc3RlbmVyIiwNCgkJImFydGlmYWN0SWQiOiAiMV83IiwNCgkJInZlcnNpb24iOiAiJSVsYXRlc3QlMjkzMCINCgl9LA0KCXsNCgkJImdyb3VwSWQiOiAib3JnLmludmVudGl2ZXRhbGVudC5wYWNrZXRsaXN0ZW5lciIsDQoJCSJhcnRpZmFjdElkIjogIjFfOCIsDQoJCSJ2ZXJzaW9uIjogIiUlbGF0ZXN0JTI5MzAiDQoJfV0NCn0=), just add the dependencies (plugin.yml, pom.xml) and register NickNamerAPI.class
