### ISSUE TITLE
Nicknamer SkinChange error

### ISSUE THREAD

**Issue by Kalmori** [InventivetalentDev/NickNamer#33]
## What steps will reproduce the problem?  
1. Using BungeeCord, Spigot 1.8.8 and the new
2. 
3. /randomskin or /skin {name} don't change my skin

## What were you expecting to happen? What happened instead?  
Skin change for me and other players | Nothing changed

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Spigot: 3.12.3
Bungee: 1.0.3

## What Spigot version are you using? *Type /version*  
1.8.8-R0.1-SNAPSHOT

## What plugins are you using? *Type /plugins*  
Spigot: NickNamer, PacketListenerApi
Bungee: NickNamerBungee

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log* 
http://hastebin.com/mehimajati.avrasm

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
- NO

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
- Don't tryed previous versions

**Comment by InventivetalentDev** [comment]
NickNamer is not a Bungeecord plugin. Please install it on your Spigot servers and install the synchronizer plugin for Bungeecord linked in the description.

**Comment by Kalmori** [comment]
Oh, ok. I left the Spigot version in Bungees folder -.- . I removedthe Spigot version and the error is gone but the Skin still not change.

**Comment by Kalmori** [comment]
Yes shure

**Comment by InventivetalentDev** [comment]
Please post the exact command you used (Including the name)

**Comment by Kalmori** [comment]
/skin Jonday {Used many more names but nothing happend}

**Comment by Kalmori** [comment]
I also used /randomskin
And befor you ask I putt a couple of names in the config.
