### ISSUE TITLE
Possible plugin incompatibility? 

### ISSUE THREAD

**Issue by Zath137** [InventivetalentDev/NickNamer#36]
## What steps will reproduce the problem?  
1.  Install on spigot server
2.  Run server
3.  Try /nick

## What were you expecting to happen? What happened instead?  
The plugin to work, changed name in UltimateCore.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.12.3
## What Spigot version are you using? *Type /version*  
git-Spigot-10d38f1-5e5cf84 (MC: 1.10.2) (ImplementingAPI version 1.10.2-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
CoreProtect, dynmap, WorldEdit, SimplePlaytime, FraceProtect, HorseStats, StarterKit, NickNamer, BetterBeds, BarAPI, VeinMiner, PlaceholderAPI, SaturationPreview, PlugMan, WildSex, Gringotts, AnvilPatch, EasyBackup, ActionHealth, BetterHorsePlugin, WorldGuard, ProtocolLib, ElytraCrafting, ChopTree3, LockettePro, AutoRestart, PermissionsEx, HourseTpWithMe, CS-CoreLib, ActionAnnouncer, Elytra, Vault, UltimateCore, PetMaster, SilkChests, InventoryFull, SignShop, SilkSpawners,  SilkSpawnersShopAddon, SignShopHotel, CraftBay, and CraftBook.
## Do you have an error log? Use [pastebin.com](http://pastebin.com/3b41J9sV). *If you're not sure, upload your whole server log*  
It shows the plugin is working fine with no error code...
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No client crash
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using spigot and it looks like it may be incompatible
[3b41J9sV.txt](http://pastebin.com/3b41J9sV)
 with some other plugins I have installed?

**Comment by InventivetalentDev** [comment]
Install PacketListenerAPI.
