### ISSUE TITLE
Leaving NickNamer running for some time throws "MySQLNonTransientConnectionException: No operations allowed after connection closed."

### ISSUE THREAD

**Issue by dwilson390** [InventivetalentDev/NickNamer#37]
#### What steps will reproduce the problem?

Leave Spigot server running for some time, an SQL error is printed to the console.
#### What were you expecting to happen? What happened instead?

Nothing, yet the console is spammed with SQL errors.
#### What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

3.12.3
#### What Spigot version are you using? _Type /version_

CraftBukkit version git-Spigot-90f61bc-29e1d72 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
#### What plugins are you using? _Type /plugins_

Plugins (20): HubBasics, TitleAdvanced, WorldEdit, PlaceholderAPI, PacketListenerApi, EchoPet, Tab, Vault, Votifier, TokenManager, LobbySwitch, ProtocolLib, BungeePortals, AAC, PowerfulPerms, NickNamer, Essentials, LiteBans, EssentialsSpawn, DeluxeChat
#### Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

http://pastebin.com/ycN6fx9x
#### Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No.  Log not applicable. 
#### Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Using BungeeCord, happens only on one server (as far as I can see) as such information provided relates to that server.  Unsure if this issue is present in earlier versions.

**Comment by InventivetalentDev** [comment]
Does this only happen if NickNamer is inactive, i.e. no name/skin changes are made for some time?  
Also, your storage type is set to _SQL_, correct?

**Comment by dwilson390** [comment]
That's correct, however it's important to note that my other three servers
don't exhibit this issue.  The one that does is the Hub server.
