### ISSUE TITLE
nicknamer

### ISSUE THREAD

**Issue by theismarius** [InventivetalentDev/NickNamer#38]
## What steps will reproduce the problem?
1. when i execute any command says i need permissions, i give permissions and still the same i need permission to execute this command
2. im using the latest version of nicknamer
3. im using spigot 1.10.2 r0.1 snapshot
   im using a tone of plugins
   no error log
   no crash
   and im using bungeecord with the bungeecord  nicknamer version

**Comment by elFlashor** [comment]
Do you by any chance have Essentials installed? I'm having the same issue as Essentials /nick command conflicts with Nicknamer /nick command, and Essentials command is run in priority it seems...
