### ISSUE TITLE
NPE on join and quit

### ISSUE THREAD

**Issue by MineTheCube** [InventivetalentDev/NickNamer#4]
## What steps will reproduce the problem?  
1. Start the server
2. Someone join or quit the server
3. Enjoy NPE :)

## What were you expecting to happen? What happened instead?  
–

## What version of the plugin are you using?
NickNamer v3.11.0
PacketListenerAPI v3.4.2

## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Plugins that may be incompatible: AAC, ViaVersion, ProtocolLib and a custom plugin that use scoreboard.

## Do you have an error log?
http://pastebin.com/raw/rmPMaFeb

## Did your client crash?
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I use Bungeecord, and it's the first time I use the plugin.

**Comment by InventivetalentDev** [comment]
Please post your complete server log. The current log doesn't contain any information I could use to resolve the issue.

**Comment by MineTheCube** [comment]
Okay, here it is: http://pastebin.com/raw/p7j5WmP3

**Comment by MineTheCube** [comment]
This [commit](https://github.com/InventivetalentDev/NickNamer/commit/0642bad0d6f2c50f0e42832bee18ddd96013d642) solved the issue ! Thanks :)
