### ISSUE TITLE
UnsupportedOperationException NickNamerAPI

### ISSUE THREAD

**Issue by ChewingG** [InventivetalentDev/NickNamer#45]
## What steps will reproduce the problem?  
1. Have use the API and have a error UnsupportedOperationException

## What were you expecting to happen? What happened instead?  
When /nick
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NickNamerAPI version 3.12.3

## What Spigot version are you using? *Type /version*  
Spigot 1.8
## What plugins are you using? *Type /plugins*  
Plugins (2): PacketListenerApi, Test 
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/p6jNm2k4
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
My Code : http://pastebin.com/QbyyMeF8

**Comment by InventivetalentDev** [comment]
The SimpleNickManager doesn't support methods like #setNick or #setSkin. 
You either need to use the PluginNickManager (`NickNamerAPI.getNickManager()`), or use the [NickDisguiseEvent](https://github.com/InventivetalentDev/NickNamer/blob/master/API/src/main/java/org/inventivetalent/nicknamer/api/event/disguise/NickDisguiseEvent.java) (which is recommended if you don't need the plugin functionalities)

**Comment by ChewingG** [comment]
I have test with NickNamerAPI.getNickManager() but i have the same error

**Comment by InventivetalentDev** [comment]
Is the NickNamer plugin enabled on your server?

**Comment by ChewingG** [comment]
No i use only the api

**Comment by InventivetalentDev** [comment]
The there's your problem 😉
