### ISSUE TITLE
InvalidPluginException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by TomberWolf** [InventivetalentDev/NickNamer#49]
## What steps will reproduce the problem?  
1. Starting Server

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NickNamer_v3.13.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Thermos 1.7.10

## Do you have an error log? 
http://pastebin.com/Qg7QK1Zy

**Comment by InventivetalentDev** [comment]
I'll just take a guess that NickNamer isn't compatible with the server platform you're using (Thermos). 
Did you try it on a regular spigot server?

**Comment by TomberWolf** [comment]
We need to use Thermos because of the Forge implemantation.
As far as I can say it's fully compatible to Spigot and Bukkit and other plugins are working fine with it.
You may want to take a look at it:

https://yivesmirror.com/downloads/thermos
