### ISSUE TITLE
Warning with packetlistenerapi on start

### ISSUE THREAD

**Issue by Doc94** [InventivetalentDev/NickNamer#5]
## What steps will reproduce the problem?  
1. start server

## What were you expecting to happen? What happened instead?  
Server generate warnings in starts (i am not secure what errors cause... i only use the api)

## What version of the plugin are you using?
3.11.3

## What Spigot version are you using? 
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins ae you using? 
MinPlayAPI, ViaVersion, ProtocolLib, PacketListenerApi, LibsDisguises, NickNamer
## Do you have an error log? 
Here http://pastebin.com/aq2sSbcV

## Additional information?
In old versions this work.

**Comment by InventivetalentDev** [comment]
Should be fixed in v3.11.4
