### ISSUE TITLE
Invalid SemVer 

### ISSUE THREAD

**Issue by yzandre** [InventivetalentDev/NickNamer#51]
Spigot 1.9.4
Nicknamer v 3.13.2
PacketListenerAPI_v3.5.2

in console: 

[Craft Scheduler Thread - 15/WARN]: [SpigetUpdate] Invalid SemVer versions specified [3132-SNAPSHOT] [3132-SNAPSHOT]

i don't have this error when i disable nicknamer

**Comment by ccegeadamcc** [comment]
I get that error on spigot 1.12 with latest version. Please help

**Comment by ccegeadamcc** [comment]
I fixed. I updated protocolsupport to latest version. And its fixed :D

**Comment by InventivetalentDev** [comment]
Ignore it. It's just a WARNing.

**Comment by xDRAKONISx** [comment]
@ccegeadamcc how did you update protocolsupport?
