### ISSUE TITLE
Papi and Nicknamer = Invalid Argument

### ISSUE THREAD

**Issue by mitchal01** [InventivetalentDev/NickNamer#52]
## What steps will reproduce the problem?  
1. 
2. 
3. 

## What were you expecting to happen? What happened instead?  
The placeholders in Papi to work 
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.13.2 SNAPSHOT
## What Spigot version are you using? *Type /version*  
craftbukkit version git-Spigot-c55900f-9856d8a (MC:110) (implementing API version 1.10-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
http://oi64.tinypic.com/2ib2np0.jpg Picture of Console what it says in game (problem) and Plugins
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No Error
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No Crash
## Additional information?  *(Are you using Bungee cord? Did it work in previous versions? etc.)*
No Just need the placeholders for Nicknamer and I have downloaded the ecloud from Papi.

**Comment by InventivetalentDev** [comment]
Uhm... Papi?

**Comment by mitchal01** [comment]
PlaceholderApi - PAPI

**Comment by InventivetalentDev** [comment]
Well, I don't have anything to do with PlaceholderAPI, so you're gonna have to figure out something out with the author of that.

**Comment by mitchal01** [comment]
Ok i will ask the main developer.

**Comment by extendedclip** [comment]
Hmm

**Comment by mitchal01** [comment]
... I got an email and I saw this I am not even sure I set this up right at the time...
