### ISSUE TITLE
MySQL/Bungeecord Data Sync Issue

### ISSUE THREAD

**Issue by Jack166** [InventivetalentDev/NickNamer#59]
## What steps will reproduce the problem?  
1. Start all Spigot Servers and the Bungeecord Server
2. Use /nickname <name> or /skin <name>
3. Switch from Spigot Server 1 to Spigot Server 2

## What were you expecting to happen? What happened instead?  
I expected that my nickname and skin would be changed on all servers. Instead of that on all other servers, except Spigot Server 1, my username and skin were my normal username and skin.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.13.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Spitgot Server 1: CraftBukkit version git-Spigot-7d78b81-d5e7885 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Spigot Server 2: CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Spigot Server 1: Plugins (46): AsyncWorldEditInjector, WorldEdit, Skript, MCDiscordIntegrator, JoinEventsPro, QuickBoard, PlaceholderAPI, PacketListenerApi, PlayerVisibilityReborn, PlugMan, SkQuery, NametagEdit, BuycraftX, LiteFly, WorldGuard, LaunchPadPlus, MCAuthenticator, AsyncWorldEdit, InventoryLock, WildSkript, PermissionsEx, LobbyCompassBungee, HCTeamsFreeze, ConditionalCommands, CommandSync, Tablist, Vault, ProtocolSupport, NickNamer, Essentials, Citizens, EssentialsChat, ViaVersion, EssentialsSpawn, ProtocolLib, LibsDisguises, AAC, CitizensCMD, React, HolographicDisplays, LiteBans, HideAndCustomPlugins, skRayFall, HolographicExtension, GadgetsMenu
Spigot Server 2: Plugins (44): AsyncWorldEditInjector, WorldEdit, Skript, JoinEventsPro, killStats, PlaceholderAPI, PacketListenerApi, PlugMan, SkQuery, NametagEdit, BuycraftX, WorldGuard, LaunchPadPlus, SpigotFly, MCAuthenticator, MVdWPlaceholderAPI, AsyncWorldEdit, SignEdit, WildSkript, PermissionsEx, HCTeamsFreeze, FeatherBoard, ConditionalCommands, CommandSync, ViaVersion, Tablist, Vault, NickNamer, Essentials, SimpleRename, KingKits, ProtocolLib, HideAndCustomPlugins, DeluxeChat, AAC, Citizens, React, BossShop, EssentialsSpawn, HolographicDisplays, LiteBans, CitizensCMD, skRayFall, LeaderHeads

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/x48NemNX (Only the log of Nicknamer)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Client did not crash

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using Bungeecord and MySQL, the Bungeecord plugin is installed on the Bungeecord Server and enabled in the config. The plugin connects to MySQL on all servers, but does not sync data, Bungeecord plugin does also not sync data.

P.S. Sorry for my English, I am Dutch.

**Comment by InventivetalentDev** [comment]
Did you enable `bungeecord` in your config?

**Comment by Jack166** [comment]
Yes, in the plugin config and in the Spigot config.
