### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by M9GLiquid** [InventivetalentDev/NickNamer#6]
## What steps will reproduce the problem?  
1. Running Your plugin and a custom plugin using JSON chat ( TextComponent(); )
2. It doesn't brake the plugin just pumps out 700 rows of errors each time you click/hover or anything else json related
3. 

## What were you expecting to happen? What happened instead?  
Should happend: No errors and my Json to be shown normally
Actually happend: Alot of Errors and my json displayed normally

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
PacketListenerAPI_v3.4.2.jar with 
NickNamer 3.11.4

## What Spigot version are you using? *Type /version*  
Spigot 1.9.4

## What plugins ae you using? *Type /plugins*  
[Plugins](http://prntscr.com/bhx5kr)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Part involving NickNamer (PacketListener)
[Partial Log](http://pastebin.com/UBYxKjU1)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No..
Full Log:
[Full Log](http://pastebin.com/GByuXjRQ)

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Test Server with my own custom plugin.

Code I used that it dislikes:
`/**
	 * Chat with Hovertext and Actions (Does currently not work on the main server, conflict)
	 * @param p - Player Instance
	 * @param text - String
	 * @param suggest - String (Suggest/Run as command)
	 * @param hoverText - String
	 * @param hoverColor - ChatColor
	 * @param textColor - ChatColor
	 * @param action - boolean (True :: Suggestive Command | False :: Run Command)
	 */
	public static void JsonChat(Player p, String text, String suggestText, String hoverText, boolean suggestive){
		text = Format(placeholders(text));
		hoverText = Format(placeholders(hoverText));
		TextComponent message = new TextComponent(text);
		if(suggestive)
			message.setClickEvent(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, suggestText));
		else
			message.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, suggestText));
		message.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder(hoverText).create()));
		p.spigot().sendMessage(message);
	}`

Regards,
Thomas

**Comment by InventivetalentDev** [comment]
Please try disabling the chat-replacement options. Does the message you try to send contain any names if nicked players?

**Comment by M9GLiquid** [comment]
No only help options for support but it might in the future as I got my own placeholder system for my own game.

I'll try disabling the chat-replacement

**Comment by M9GLiquid** [comment]
Did not work by disabling the chat...

Config.yml:
`replace:
  chat:
    # Replace names in messages sent by players
    player: false

    # Replaces names in ALL outgoing messages
    out: false
    in:
      # Replace names in incoming commands
      command: false

      # Replace names in general (non-command) incoming messages
      general: false
  scoreboard: false
  scoreboardScore: false
  scoreboardTeam: false
  tabComplete:
    chat: false

random:
  join:
    nick: false
    skin: false
  nick:
  - "inventivetalent"
  - "md_5"
  - mojang: # Name category
    - "jeb_"
    - "Notch"
    - "Dinnerbone"
  skin:
  - "md_5"
  - "inventivetalent"

names:
  # Format for names, for example '&9%s' would color all names blue. Note: names can't be longer than 16 charcters and will be shortened.
  format: "%s"

  # Format for names in chat messages
  chatFormat: "%s&r"

#Enable this if this server is behind a BungeeCord server
bungeecord: false

storage:
  # Storage type
  # - temporary
  #     saves all data in memory until the server is stopped
  # - local (recommended)
  #     creates a local database or uses the database specified in bukkit.yml
  # - sql
  #     uses an SQL server
  # - redis
  #     uses a Redis server
  type: "local"
  sql:
    address: "jdbc:mysql://localhost:3306/minecraft"
    user: ""
    pass: ""
  redis:
    host: "localhost"
    port: 6379
    pass: ""
    max-connections: 4


messages:
  command:
    name:
      changed: "&aChanged &b%player%'s &aname to &b%name%&a."
      cleared: "&aCleared &b%player%'s &aname"
      list:
        used: "&eUsed names:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified name is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used names"
    skin:
      changed: "&aChanged &b%player%'s &askin to &b%skin%''s&a skin."
      cleared: "&aCleared &b%player%'s &askin"
      list:
        used: "&eUsed names:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified skin is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used skins"
    error:
      unknown: "&cUnknown error while executing command. See console for details."
      permission: "&cYou are missing the following permission: %s"
      illegalSender: "&cThis command is only available to players"
      unhandled: "&cInternal exception. See console for details."
      length:
       short: "&cMissing arguments. Usage: %s"
       long: "&cToo many arguments. Usage: %s"
      parse: "&cFailed to parse argument '%s' to %s"
      target:
        notFound: "&cPlayer could not be found"

# Disable the features below, if you're only interested in utilizing the API.
pluginFeatures:
  commands:
    general: true
    nick: true
    skin: true
`

**Comment by M9GLiquid** [comment]
*Updated the url's in here :D

**Comment by M9GLiquid** [comment]
Solvable Solution:
Other servers have to use Package Json (example: FancyMessage)
As it does not interfere with other Json Packaging

**Comment by InventivetalentDev** [comment]
Fixed in version 3.11.7.
