### ISSUE TITLE
Error on version 3.13.3

### ISSUE THREAD

**Issue by comonier** [InventivetalentDev/NickNamer#63]
how can i config to not show that error ?
i dont have mysql database

>>> https://hastebin.com/ezipayegig.css

Spigot 1.12

**Comment by InventivetalentDev** [comment]
`LOCAL STORAGE IS NO LONGER SUPPORTED! SWITCH TO SQL OR TEMP.`

**Comment by comonier** [comment]
How can i do that ? i havent sql database, and do not understand what Temp means, can you link me a tutorial how to solve that problem ?

**Comment by sergservis** [comment]
Return removes support for the 'local' storage type!
