### ISSUE TITLE
The changes, after a while, fade. How can we solve?

### ISSUE THREAD

**Issue by Erenil** [InventivetalentDev/NickNamer#69]
Good evening!
I noticed in this period of trial of your plugin that there is a problem with it.
When i perform the command /nickname or /skin i can change nickname and skin of a player, but after a while the changes aren't visible. After 5/10 minutes the changes aren't applied to the player. Sometimes it starts to work, but then it stops and the changes disappear.
Every 10 minutes we have to perform the command /nickname and /skin to change it for a player.
I'm here to ask you, if you can solve this problem. We would like to have permanent changes after perform the command.
I'm talking for Fargus5

-We're using the 3.14.0 snapshot of your plugin

-This server is running CraftBukkit version git-Spigot-bb614f8-595eaaa (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

-Chess, Combatant, Teamspeakbot, Lift, Vehicles, PlugMan, MoreItems, AutomaticInventory, SimpleAntiProxy, RealCigaret, MaintenanceMode, DoorCloser, SimpleAPI, Itemizer, Timber, Skript, CreatureSpawners, HelpTickets, Realistic-Swimming, InvRestore2, AgarthaLib, Modifyworld, VehiclesFlags, Tornado, WitcheryX, ActionBarAPI, PremiumTurrets, RealisticFish, MCCore, BlocksAlive2, FastAsyncWorldEdit, PermissionsEx, FurnaceEditor, ArmorstandEditAndAnimator, RPGHealthIndicator, BannerBuilder, PEXPlayersRemover, SoundEvents, RPGFood, RealWeatherAndTime, FastAsyncVoxelSniper, EntityOptions, PlaceholderAPI, LetterBox, NametagEdit, GeneralLib, CarlTheCreeper, RPGMiner, ProdigyGadget, CreatureSpawnersPatch111, TitleAPI, SuperTrails, VoxelSniper, AdvancedCraftingTable, Edit_Mobs, AngelBlock, EpicWorldGenerator, Graves, ParticleLIB, PartySystem, MOTD, LagMonitor, ItemAPI, LightAPI, ItemDrop, CoreProtect, WorldEdit, CityWorld, OpenInv, MagnetChests, CrackShot, Scoreboard, MotionDetector, Votifier, DUM, BetterRealismPro, SpawnerEditor, TreasureChest, MimicChest, SQLibrary, EffectLib, BiomeTempRemastered, Natrolite, Vault, MassiveCore, CreativeGates, DreamFish, GrowingOres, AddLight, CustomArrow, MyCommand, EpicNetherGenerator, GUIPlus, ScoreboardAddonBiomeTempRemastered, MessageAnnouncer, Multiverse-Core, Calendar, DabCore, JusticeSystem, WorldGuard, AngryCuccos, SignColors, ResourceGens, GeneralMarket, RegrowingBlocks, InfernalMobs, Essentials, SpigotLib, HeadDatabase, DiscordSRV, VoteListener, AdvancedAchievements, MysteryBoxes, ProdigyDisaster, OpenAudioMc, Repuska, MoneyPickup, StarGate, EssentialsGeoIP, WorldGuardPushBack, NavyCraft, Statz, Bank, ServerTutorialPlus, SimplePets, ProtocolLib, Citizens, EssentialsChat, WGRegionEvents, Hotels, WorldEditSelectionVisualizer, BankBalTop, Thirst, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, Blacksmith, ChangeSkin, LibsDisguises, RealVillagerTowns, RPGDeath, RPGHorses, AuthMe, HolographicDisplays, Spartan, MythicMobs, Quests, ChatItem, CommandNPC, PremiumVanish, Kingdoms, Sentinel, FactionMobs, DisguiseAbilities, TransportPipes, ProtectionLib, WorldGuardExtraFlags, ChatActions, MythicMobsExtension, Skills, LiteBans, ChatBubbles, ShopChest, MythicArtifacts, TitleManager, Cartographer, Plan, FurnitureLib, CartographerMapper, DiceFurniture, RPGPlayerLeveling, RPGInventory, RPGPlayerLevelingReplacer, RPGMagic

-We didn't notice any error in the console.

-Our client didn't crash.

-It's the first time that we're approaching with this plugin, so we cannot say if it worked for other version.

**Comment by InventivetalentDev** [comment]
Please post a copy of your `config.yml`

**Comment by Fargus5** [comment]
Please to find it here:

https://pastebin.com/qdff9Pxn

**Comment by InventivetalentDev** [comment]
Alright, pretty sure this is caused by the cache keeping the datase's data in memory expires too soon. This usually shouldn't be a problem, since it refreshes automatically. But in your case it seems to completely reset the player's data.
I'll try to make it more reliable for the next version :)

**Comment by Fargus5** [comment]
The problem has not be solved.
Name and skins changes automatically after a while

**Comment by InventivetalentDev** [comment]
Well, I have no idea what's going on on your server then. I've fixed all issues I could find related to what you described and didn't have any problems in the end after testing for about an hour.
You might want to try NickNamer by itself without any other plugins, maybe it's just an incompatibility.

**Comment by sergservis** [comment]
The problem has not be solved. Nicks are disappearing.
