### ISSUE TITLE
/randomskin and /skin dont work, the skin want to update but the skin is still your own skin.

### ISSUE THREAD

**Issue by LimitedGames** [InventivetalentDev/NickNamer#7]
/randomskin and /skin doent work. you still have your own skin.

Config: Default

plugin version: 3.11.5

mc version: bukkit 1.8.3

Plugin's (test server): WorldEdit, Essentials, Groupmanager, PacketListenerApi VotingPoll, CustomJoinItems, Vault, ProtocolLib, NickNamer, ChestCommands

Errors:

20.06 15:26:00 [Server] [Informatie] redstoneronald issued server command: /randomskin 

20.06 15:26:00 [Server] [Informatie] redstoneronald issued server command: /skin inventivetalent 

20.06 15:26:00 [Server] WARN Exception in thread "pool-3-thread-16" 

20.06 15:26:00 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin NickNamer v3.11.5 generated an exception while executing task 64 

20.06 15:26:00 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) 

20.06 15:26:00 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 

20.06 15:26:00 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 

20.06 15:26:00 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) 

20.06 15:26:00 [Server] [Informatie] Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='skinCache', types=[]}] in class class net.minecraft.server.v1_8_R2.TileEntitySkull 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:142) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.loadSkinHandle(SkinLoader.java:114) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.loadSkin(SkinLoader.java:99) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.api.PluginNickManager$5.run(PluginNickManager.java:250) 

20.06 15:26:00 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:53) 

20.06 15:26:00 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 

20.06 15:26:00 [Server] [Informatie] ... 3 more 

20.06 15:26:00 [Server] [Informatie] Caused by: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='skinCache', types=[]}] in class class net.minecraft.server.v1_8_R2.TileEntitySkull 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:186) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:39) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.resolve(FieldResolver.java:85) 

20.06 15:26:00 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:135) 

20.06 15:26:00 [Server] [Informatie] ... 8 more 

20.06 15:26:08 [Server] ERROR Failed to disguise profile 

20.06 15:26:08 [Server] [Informatie] java.lang.RuntimeException: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='skinCache', types=[]}] in class class net.minecraft.server.v1_8_R2.TileEntitySkull 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:142) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfile(SkinLoader.java:106) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.api.PacketListener.disguiseProfile(PacketListener.java:284) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.api.PacketListener.onSend(PacketListener.java:110) [NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:109) [PacketListenerAPI_v3.4.2.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:146) [PacketListenerAPI_v3.4.2.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:111) [PacketListenerAPI_v3.4.2.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:168) [PacketListenerAPI_v3.4.2.jar:?] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327) [(mg)%20ProtocolLib.jar:?] 

20.06 15:26:08 [Server] [Informatie] at net.minecraft.server.v1_8_R2.NetworkManager$4.run(NetworkManager.java:189) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361) [(mg)%20ProtocolLib.jar:?] 

20.06 15:26:08 [Server] [Informatie] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [cb1.8.3.jar:git-Bukkit-0a645a2] 

20.06 15:26:08 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91] 

20.06 15:26:08 [Server] [Informatie] Caused by: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='skinCache', types=[]}] in class class net.minecraft.server.v1_8_R2.TileEntitySkull 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:186) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:39) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.reflection.resolver.FieldResolver.resolve(FieldResolver.java:85) ~[NickNamer_v3.11.5.jar:?] 

20.06 15:26:08 [Server] [Informatie] at org.inventivetalent.nicknamer.api.SkinLoader.getSkinProfileHandle(SkinLoader.java:135) ~[NickNamer_v3.11.5.jar:?]

**Comment by InventivetalentDev** [comment]
![](https://media.inventivetalent.org/i/Screenshot-at-20-06-16-18-24-35.png)
-> https://pastebin.com

**Comment by LimitedGames** [comment]
good?.... http://pastebin.com/UmbpsBcU

**Comment by InventivetalentDev** [comment]
Please use Spigot. Bukkit isn't fully compatible with my plugins.
