### ISSUE TITLE
use ProtocolLib instead of PacketListenerAPI

### ISSUE THREAD

**Issue by FrozenBeard** [InventivetalentDev/NickNamer#73]
99% of people will more likely already be using ProtocolLib already with their anticheat and existing plugins, having to add yet ANOTHER packet plugin just as a dependency is silly, ProtocolLib is perfectly fine why have to have ANOTHER dependency.

**Comment by FrozenBeard** [comment]
Bit of a rubbish bot. Bump.

**Comment by FrozenBeard** [comment]
Bloody rubbish bot!

**Comment by InventivetalentDev** [comment]
NickNamer and pretty much all of my other plugins have been built upon the PacketListener framework as it is a lot less resource intensive and I have no plans of changing it any time soon.
