### ISSUE TITLE
everything is not working!

### ISSUE THREAD

**Issue by felix920506** [InventivetalentDev/NickNamer#74]
## What steps will reproduce the problem?  
1. drop the jar file in the plugins folder
2. restart the server
3. 

## What were you expecting to happen? What happened instead?  
I was expecting /nick would change my nickname but nothing happened

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.15.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
final 1.12.2 build

## What plugins are you using? *Type /plugins*  
![2018-10-28_21 50 02](https://user-images.githubusercontent.com/25688628/47616720-94080480-dafb-11e8-9e00-c9a34dd5f8a4.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
no
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
using bungeecord, sync plugin is installed

**Comment by InventivetalentDev** [comment]
Install PacketListenerAPI

**Comment by felix920506** [comment]
should i install it on bungeecord, the server , or both?

**Comment by InventivetalentDev** [comment]
only the server

**Comment by felix920506** [comment]
installed it. still not working :(

**Comment by InventivetalentDev** [comment]
Paste your console log, please.
