### ISSUE TITLE
Not loading block textures (empty world)

### ISSUE THREAD

**Issue by OBitzs** [InventivetalentDev/NickNamer#8]
## What steps will reproduce the problem?  
1. Reloading
2. logging in
3. 

## What were you expecting to happen? What happened instead?  
The world to render, it spawned me in a world where the block textured did not load

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
NickNamer version 3.11.5

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-6016ac7-7964365 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

## What plugins ae you using? *Type /plugins*  
WorldEdit, CoreProtect, PacketListenerApi, AdvancedBan, Vault, PlayerPoints, PermissionsEx, AdvancedAbilities, bChatManager, React, dynmap, EpicRename, NickNamer, SettlerCraft

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/qXZeDz8C

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
N.A

**Comment by InventivetalentDev** [comment]
Caused by some weird issues with some Minecraft clients. Press **F3+A** to reload your world.  
Currently there's no reliable way to fix this.
