### ISSUE TITLE
Java version-error even when using 8+

### ISSUE THREAD

**Issue by Th3Shadowbroker** [InventivetalentDev/NickNamer#83]
## What steps will reproduce the problem?  
1. Start the server

## What were you expecting to happen? What happened instead?  
Normal startup. 
Two exceptions where thrown that caused the plugin to disable itself. The second was caused by the first.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.16.0-SNAPSHOT build from source not from the link from spigot.

## What Spigot version are you using? *Type /version*  
Dosen't matter as java.version is a env.-variable. But for the protocol ^^
I were using spigots final build for 1.12.2

## What plugins are you using? *Type /plugins*  
PlaceholderAPI, PacketListenerApi, NickNamer

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Sure. https://pastebin.com/UkEkvHDY

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Just a question. I saw you changed one of the lines that caused the exception in 2d824ca. So I guess a similar problem occurred earlier. However,  in my case the java version starts with a 1 followed by the "minor" version. Were you using another version that used another version format or is their a mistake on my site? In case it's not I'll leave a PR below :smile:

**Comment by InventivetalentDev** [comment]
I think the change you mentioned was in response to another similar issue detecting the wrong java version. What's the version format of your Java?

**Comment by Th3Shadowbroker** [comment]
Something like 1.8.0_152

**Comment by InventivetalentDev** [comment]
Removed the runtime exception that keeps the plugin from starting, so hopefully this should work in any environment.

**Comment by Tinkot** [comment]
this still happens. i'm using java 11
`Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
`

**Comment by Th3Shadowbroker** [comment]
Hi @Tinkot, I tried to replicate your problem. It looks like oracle changed their opinion on correct version-naming ^^ 

However, it looks like we have two problems here.

1. The first problem is, that the [latest release](https://github.com/InventivetalentDev/NickNamer/releases/tag/3.16.0-SNAPSHOT), was compiled with an older main-class which threw a RuntimeException when a version below java 8 was used. That exception was later removed by inventive (as you can see in 9b99a60dacd49458d24e942360ffae12ac7fa8a2) but no new release was created.

2. The second problem is, that it looks like oracle changed their version-format. For comparsion:
 - Java 8 and lower: 1.8.0_231
 - Java 11+: 11.0.5

According to [Line 185](https://github.com/InventivetalentDev/NickNamer/blob/52b09e03ebbc6484f8b6c9c67ee493d86aa42c42/Plugin/src/main/java/org/inventivetalent/nicknamer/NickNamerPlugin.java#L158) in the plugins main-class the check is performed on the second number, as this number was the only one that changed in the past.
