### ISSUE TITLE
The plugin fails to disguise profiles on Spigot 1.8

### ISSUE THREAD

**Issue by ALCC01** [InventivetalentDev/NickNamer#9]
## What steps will reproduce the problem?  
1. Install the plugin on a Spigot 1.8 instance
2. Try to change the nickname of a player (both via commands and API)
3. Enjoy the stacktrace

## What were you expecting to happen? What happened instead?  
It's pretty straight-forward, the plugin should change the player's name, instead it fails and produces some error logs.

## What version of the plugin are you using?
3.11.5. The PacketListenerAPI version may also be relevant, 3.4.2

## What Spigot version are you using? 
```git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)```
## What plugins are you using?
```PacketListenerApi, NickNamer```

## Do you have an error log?
The [same error](http://paste.ubuntu.com/17846405/) is produced repeatedly as the plugin tries to send packets.

## Additional information?
Looks fine while running on Spigot >=1.8.3

**Comment by InventivetalentDev** [comment]
Please check your startup log for a similar message: `[ReflectionHelper] Version is v1_10_R1 (11001)`

**Comment by InventivetalentDev** [comment]
Fixed in version 3.11.6.
