### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Jakaboii** [InventivetalentDev/NickNamer#99]
## What steps will reproduce the problem?  
1. Put the plugin & all required plugins on a bungeecord server
2. Start the server

## What were you expecting to happen? What happened instead?  
I expected the plugin to load, it just sent a startup error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.17.0-SNAPSHOT

## Do you have an error log?
https://hatebin.com/sbjttnkrac

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using [Flamecord](https://www.2l-studios.com/flamecord/downloads.php)

**Comment by InventivetalentDev** [comment]
NickNamer is a paper/bukkit plugin and will not work on a Bunggecord server.  

There's a section on the plugin page explaining how to synchronize data on a bungeecord network.
